import type { reviewSourceTypes, stabilityTypes, terrains } from "@/lib/domain/shoes";

type Terrain = (typeof terrains)[number];
type Stability = (typeof stabilityTypes)[number];
type ReviewSourceType = (typeof reviewSourceTypes)[number];

export interface SeedBrand {
  name: string;
  slug: string;
  websiteUrl: string;
}

export interface SeedShoe {
  brandSlug: string;
  name: string;
  slug: string;
  category:
    | "road-daily"
    | "road-workout"
    | "road-race"
    | "trail-daily"
    | "trail-race"
    | "track-spikes"
    | "hiking-fastpack";
  stability: Stability;
  terrain: Terrain;
  usageSummary: string;
}

export interface SeedRelease {
  shoeSlug: string;
  versionName: string;
  releaseYear: number;
  msrpUsd: string;
  isCurrent: boolean;
  isPlated: boolean;
  foam: string;
  notes: string;
}

export interface SeedSpec {
  releaseKey: string;
  weightOzMen: string;
  heelStackMm: number;
  forefootStackMm: number;
  dropMm: number;
  fitNotes: string;
}

export interface SeedReviewSource {
  name: string;
  slug: string;
  sourceType: ReviewSourceType;
  siteUrl: string;
  baseDomain: string;
}

export interface SeedReviewAuthor {
  sourceSlug: string;
  displayName: string;
  profileUrl: string;
}

export interface SeedReview {
  releaseKey: string;
  sourceSlug: string;
  authorName: string;
  sourceUrl: string;
  title: string;
  excerpt: string;
  scoreNormalized100: number;
  originalScoreValue: string;
  originalScoreScale: string;
  sentiment: "positive" | "mixed" | "negative";
  status: "pending" | "approved" | "rejected" | "flagged";
  publishedAt: string;
}

export interface SeedCrawlSource {
  reviewSourceSlug: string;
  importerKey: string;
  targetType: "search" | "listing" | "api";
  targetUrl: string;
  searchPattern: string;
  cadenceLabel: string;
  notes: string;
}

export const seedBrands: SeedBrand[] = [
  { name: "Nike", slug: "nike", websiteUrl: "https://www.nike.com" },
  { name: "Saucony", slug: "saucony", websiteUrl: "https://www.saucony.com" },
  { name: "Hoka", slug: "hoka", websiteUrl: "https://www.hoka.com" },
  { name: "Brooks", slug: "brooks", websiteUrl: "https://www.brooksrunning.com" },
  { name: "ASICS", slug: "asics", websiteUrl: "https://www.asics.com" },
  { name: "New Balance", slug: "new-balance", websiteUrl: "https://www.newbalance.com" },
  { name: "Altra", slug: "altra", websiteUrl: "https://www.altrarunning.com" },
  { name: "Mizuno", slug: "mizuno", websiteUrl: "https://mizunousa.com" },
  { name: "PUMA", slug: "puma", websiteUrl: "https://us.puma.com" },
  { name: "Adidas", slug: "adidas", websiteUrl: "https://www.adidas.com" },
  { name: "Salomon", slug: "salomon", websiteUrl: "https://www.salomon.com" },
];

export const seedShoes: SeedShoe[] = [
  {
    brandSlug: "nike",
    name: "Pegasus",
    slug: "nike-pegasus",
    category: "road-daily",
    stability: "neutral",
    terrain: "road",
    usageSummary: "Everyday mileage for runners who want a familiar neutral trainer.",
  },
  {
    brandSlug: "nike",
    name: "Vomero",
    slug: "nike-vomero",
    category: "road-daily",
    stability: "neutral",
    terrain: "road",
    usageSummary: "Max-cushion daily training for runners who want plush comfort and a smooth rocker.",
  },
  {
    brandSlug: "nike",
    name: "Alphafly",
    slug: "nike-alphafly",
    category: "road-race",
    stability: "neutral",
    terrain: "road",
    usageSummary: "Top-end road racing for marathon and half marathon efforts at goal pace.",
  },
  {
    brandSlug: "saucony",
    name: "Endorphin Speed",
    slug: "saucony-endorphin-speed",
    category: "road-workout",
    stability: "neutral",
    terrain: "road",
    usageSummary: "Fast training shoe for workouts and long runs with some bounce.",
  },
  {
    brandSlug: "saucony",
    name: "Triumph",
    slug: "saucony-triumph",
    category: "road-daily",
    stability: "neutral",
    terrain: "road",
    usageSummary: "Premium daily mileage and recovery comfort with a soft, high-stack ride.",
  },
  {
    brandSlug: "saucony",
    name: "Ride",
    slug: "saucony-ride",
    category: "road-daily",
    stability: "neutral",
    terrain: "road",
    usageSummary: "Versatile everyday trainer built to cover easy runs, errands, and steady mileage.",
  },
  {
    brandSlug: "saucony",
    name: "Guide",
    slug: "saucony-guide",
    category: "road-daily",
    stability: "stability",
    terrain: "road",
    usageSummary: "Guided daily mileage for runners who want a stable platform without a hard correction feel.",
  },
  {
    brandSlug: "hoka",
    name: "Mach",
    slug: "hoka-mach",
    category: "road-workout",
    stability: "neutral",
    terrain: "road",
    usageSummary: "Lightweight trainer for runners who want a snappy but non-plated ride.",
  },
  {
    brandSlug: "brooks",
    name: "Ghost",
    slug: "brooks-ghost",
    category: "road-daily",
    stability: "neutral",
    terrain: "road",
    usageSummary: "Dependable neutral daily trainer for easy mileage and all-around consistency.",
  },
  {
    brandSlug: "brooks",
    name: "Glycerin",
    slug: "brooks-glycerin",
    category: "road-daily",
    stability: "neutral",
    terrain: "road",
    usageSummary: "Plush daily training built around soft landings and smooth, long-run comfort.",
  },
  {
    brandSlug: "brooks",
    name: "Adrenaline GTS",
    slug: "brooks-adrenaline-gts",
    category: "road-daily",
    stability: "stability",
    terrain: "road",
    usageSummary: "Structured daily training for runners who want support without giving up versatility.",
  },
  {
    brandSlug: "asics",
    name: "GEL-Nimbus",
    slug: "asics-gel-nimbus",
    category: "road-daily",
    stability: "neutral",
    terrain: "road",
    usageSummary: "High-cushion road mileage with a soft, smooth feel for easy and long runs.",
  },
  {
    brandSlug: "asics",
    name: "Novablast",
    slug: "asics-novablast",
    category: "road-workout",
    stability: "neutral",
    terrain: "road",
    usageSummary: "Energetic daily training for runners who want bounce and faster turnover.",
  },
  {
    brandSlug: "asics",
    name: "GEL-Kayano",
    slug: "asics-gel-kayano",
    category: "road-daily",
    stability: "stability",
    terrain: "road",
    usageSummary: "Flagship stability mileage with guided cushioning and a soft, protective ride.",
  },
  {
    brandSlug: "asics",
    name: "Superblast",
    slug: "asics-superblast",
    category: "road-workout",
    stability: "neutral",
    terrain: "road",
    usageSummary: "High-stack super trainer for runners who want one shoe to cover long runs and uptempo work.",
  },
  {
    brandSlug: "new-balance",
    name: "Fresh Foam X 1080",
    slug: "new-balance-1080",
    category: "road-daily",
    stability: "neutral",
    terrain: "road",
    usageSummary: "Soft everyday road mileage with a smooth rocker and broad comfort range.",
  },
  {
    brandSlug: "new-balance",
    name: "FuelCell Rebel",
    slug: "new-balance-rebel",
    category: "road-workout",
    stability: "neutral",
    terrain: "road",
    usageSummary: "Lightweight daily speedwork for runners who want a flexible, energetic forefoot.",
  },
  {
    brandSlug: "new-balance",
    name: "Fresh Foam X More",
    slug: "new-balance-more",
    category: "road-daily",
    stability: "neutral",
    terrain: "road",
    usageSummary: "High-cushion comfort trainer focused on easy mileage and recovery days.",
  },
  {
    brandSlug: "hoka",
    name: "Clifton",
    slug: "hoka-clifton",
    category: "road-daily",
    stability: "neutral",
    terrain: "road",
    usageSummary: "Streamlined daily trainer with moderate cushioning and HOKA's easy rocker feel.",
  },
  {
    brandSlug: "hoka",
    name: "Bondi",
    slug: "hoka-bondi",
    category: "road-daily",
    stability: "neutral",
    terrain: "road",
    usageSummary: "Soft max-cushion road mileage with a highly protective platform.",
  },
  {
    brandSlug: "hoka",
    name: "Cielo X1",
    slug: "hoka-cielo-x1",
    category: "road-race",
    stability: "neutral",
    terrain: "road",
    usageSummary: "High-stack carbon racer and super trainer crossover for fast road efforts.",
  },
  {
    brandSlug: "hoka",
    name: "Speedgoat",
    slug: "hoka-speedgoat",
    category: "trail-daily",
    stability: "neutral",
    terrain: "trail",
    usageSummary: "High-cushion trail mileage with strong grip for technical and long off-road runs.",
  },
  {
    brandSlug: "altra",
    name: "Torin",
    slug: "altra-torin",
    category: "road-daily",
    stability: "neutral",
    terrain: "road",
    usageSummary: "Zero-drop daily mileage for runners who want a natural-footshape fit on the road.",
  },
  {
    brandSlug: "altra",
    name: "Lone Peak",
    slug: "altra-lone-peak",
    category: "trail-daily",
    stability: "neutral",
    terrain: "trail",
    usageSummary: "Iconic trail mileage built around zero-drop geometry and a roomy forefoot.",
  },
  {
    brandSlug: "altra",
    name: "Vanish Carbon",
    slug: "altra-vanish-carbon",
    category: "road-race",
    stability: "neutral",
    terrain: "road",
    usageSummary: "Zero-drop carbon race shoe for runners who want speed without leaving the Altra fit philosophy.",
  },
  {
    brandSlug: "brooks",
    name: "Cascadia",
    slug: "brooks-cascadia",
    category: "trail-daily",
    stability: "stability",
    terrain: "trail",
    usageSummary: "Protective trail mileage with a stable platform for varied terrain and long days outside.",
  },
  {
    brandSlug: "saucony",
    name: "Peregrine",
    slug: "saucony-peregrine",
    category: "trail-daily",
    stability: "neutral",
    terrain: "trail",
    usageSummary: "Versatile trail running with reliable grip and enough protection for mixed off-road use.",
  },
  {
    brandSlug: "nike",
    name: "Pegasus Trail",
    slug: "nike-pegasus-trail",
    category: "trail-daily",
    stability: "neutral",
    terrain: "trail",
    usageSummary: "Road-to-trail versatility for runners who want one shoe for lighter off-road mileage.",
  },
  {
    brandSlug: "asics",
    name: "Trabuco Max",
    slug: "asics-trabuco-max",
    category: "trail-daily",
    stability: "neutral",
    terrain: "trail",
    usageSummary: "High-cushion trail miles with a rolling feel and more protection for longer efforts.",
  },
  {
    brandSlug: "adidas",
    name: "Terrex Agravic Speed Ultra",
    slug: "adidas-terrex-agravic-speed-ultra",
    category: "trail-race",
    stability: "neutral",
    terrain: "trail",
    usageSummary: "Fast trail racing and long mountain efforts with high cushioning and aggressive grip.",
  },
  {
    brandSlug: "salomon",
    name: "Speedcross",
    slug: "salomon-speedcross",
    category: "trail-daily",
    stability: "neutral",
    terrain: "trail",
    usageSummary: "Iconic grip-first trail running for muddy, soft, and technical terrain.",
  },
  {
    brandSlug: "mizuno",
    name: "Wave Rider",
    slug: "mizuno-wave-rider",
    category: "road-daily",
    stability: "neutral",
    terrain: "road",
    usageSummary: "Classic neutral road trainer with a firmer, smoother traditional training feel.",
  },
  {
    brandSlug: "mizuno",
    name: "Wave Sky",
    slug: "mizuno-wave-sky",
    category: "road-daily",
    stability: "neutral",
    terrain: "road",
    usageSummary: "Premium cushioned mileage for runners who want softness without losing structure.",
  },
  {
    brandSlug: "puma",
    name: "Deviate NITRO",
    slug: "puma-deviate-nitro",
    category: "road-workout",
    stability: "neutral",
    terrain: "road",
    usageSummary: "Plated training built to bring race-shoe energy into everyday faster sessions.",
  },
  {
    brandSlug: "puma",
    name: "Velocity NITRO",
    slug: "puma-velocity-nitro",
    category: "road-daily",
    stability: "neutral",
    terrain: "road",
    usageSummary: "Versatile daily mileage with a softer ride and broad all-around use case.",
  },
  {
    brandSlug: "adidas",
    name: "Adizero Boston",
    slug: "adidas-adizero-boston",
    category: "road-workout",
    stability: "neutral",
    terrain: "road",
    usageSummary: "Firm, efficient workout mileage with race-line geometry and training durability.",
  },
  {
    brandSlug: "adidas",
    name: "Adizero Adios Pro",
    slug: "adidas-adizero-adios-pro",
    category: "road-race",
    stability: "neutral",
    terrain: "road",
    usageSummary: "Top-end road racing focused on marathon pace efficiency and elite-level turnover.",
  },
  {
    brandSlug: "salomon",
    name: "Aero Glide",
    slug: "salomon-aero-glide",
    category: "road-daily",
    stability: "neutral",
    terrain: "road",
    usageSummary: "Road daily mileage with a smooth, highly cushioned ride and a secure upper feel.",
  },
];

export const seedReleases: SeedRelease[] = [
  {
    shoeSlug: "nike-pegasus",
    versionName: "Pegasus 40",
    releaseYear: 2023,
    msrpUsd: "130.00",
    isCurrent: false,
    isPlated: false,
    foam: "React",
    notes: "Prior-generation daily trainer with the familiar Pegasus fit and a firmer ride than Pegasus 41.",
  },
  {
    shoeSlug: "nike-pegasus",
    versionName: "Pegasus 41",
    releaseYear: 2024,
    msrpUsd: "140.00",
    isCurrent: true,
    isPlated: false,
    foam: "ReactX",
    notes: "Mainstream daily trainer with broad fit familiarity.",
  },
  {
    shoeSlug: "nike-vomero",
    versionName: "Vomero 18",
    releaseYear: 2025,
    msrpUsd: "150.00",
    isCurrent: true,
    isPlated: false,
    foam: "ZoomX + ReactX",
    notes: "Maximum-cushion road trainer with a high stack and soft rocker for easy mileage.",
  },
  {
    shoeSlug: "nike-alphafly",
    versionName: "Alphafly 3",
    releaseYear: 2024,
    msrpUsd: "285.00",
    isCurrent: true,
    isPlated: true,
    foam: "ZoomX",
    notes: "Elite road racing shoe with a carbon plate, aggressive rocker, and Air Zoom pods.",
  },
  {
    shoeSlug: "saucony-endorphin-speed",
    versionName: "Endorphin Speed 3",
    releaseYear: 2023,
    msrpUsd: "170.00",
    isCurrent: false,
    isPlated: true,
    foam: "PWRRUN PB",
    notes: "Earlier versatile plated trainer with a broad fan base across workouts and long runs.",
  },
  {
    shoeSlug: "saucony-endorphin-speed",
    versionName: "Endorphin Speed 4",
    releaseYear: 2024,
    msrpUsd: "170.00",
    isCurrent: true,
    isPlated: true,
    foam: "PWRRUN PB",
    notes: "Versatile plated trainer positioned between daily and race use.",
  },
  {
    shoeSlug: "saucony-triumph",
    versionName: "Triumph 21",
    releaseYear: 2023,
    msrpUsd: "160.00",
    isCurrent: false,
    isPlated: false,
    foam: "PWRRUN+",
    notes: "Prior Triumph generation built around soft long-run comfort and premium upper feel.",
  },
  {
    shoeSlug: "saucony-triumph",
    versionName: "Triumph 22",
    releaseYear: 2024,
    msrpUsd: "160.00",
    isCurrent: true,
    isPlated: false,
    foam: "PWRRUN PB",
    notes: "Plusher premium trainer that moves the Triumph line toward a softer, bouncier ride.",
  },
  {
    shoeSlug: "saucony-ride",
    versionName: "Ride 17",
    releaseYear: 2024,
    msrpUsd: "140.00",
    isCurrent: false,
    isPlated: false,
    foam: "PWRRUN+",
    notes: "Previous Ride version with a versatile daily profile and softer transition than older rides.",
  },
  {
    shoeSlug: "saucony-ride",
    versionName: "Ride 18",
    releaseYear: 2025,
    msrpUsd: "140.00",
    isCurrent: true,
    isPlated: false,
    foam: "PWRRUN+",
    notes: "Do-it-all daily trainer with lighter foam and stronger all-day versatility.",
  },
  {
    shoeSlug: "saucony-guide",
    versionName: "Guide 18",
    releaseYear: 2025,
    msrpUsd: "140.00",
    isCurrent: true,
    isPlated: false,
    foam: "PWRRUN",
    notes: "Stable daily trainer with a broad platform and CenterPath guidance.",
  },
  {
    shoeSlug: "hoka-mach",
    versionName: "Mach 5",
    releaseYear: 2023,
    msrpUsd: "140.00",
    isCurrent: false,
    isPlated: false,
    foam: "PROFLY+",
    notes: "Previous lightweight trainer known for its soft-meets-snappy ride and easy turnover.",
  },
  {
    shoeSlug: "hoka-mach",
    versionName: "Mach 6",
    releaseYear: 2024,
    msrpUsd: "140.00",
    isCurrent: true,
    isPlated: false,
    foam: "Super Critical EVA",
    notes: "Lightweight neutral trainer without a plate.",
  },
  {
    shoeSlug: "brooks-ghost",
    versionName: "Ghost 16",
    releaseYear: 2024,
    msrpUsd: "140.00",
    isCurrent: false,
    isPlated: false,
    foam: "DNA Loft v3",
    notes: "Reliable neutral trainer with a familiar 12mm drop and broad daily-run appeal.",
  },
  {
    shoeSlug: "brooks-ghost",
    versionName: "Ghost 17",
    releaseYear: 2025,
    msrpUsd: "150.00",
    isCurrent: true,
    isPlated: false,
    foam: "DNA Loft v3",
    notes: "Current Ghost with slightly more underfoot cushioning and the same dependable training role.",
  },
  {
    shoeSlug: "brooks-glycerin",
    versionName: "Glycerin 22",
    releaseYear: 2025,
    msrpUsd: "165.00",
    isCurrent: true,
    isPlated: false,
    foam: "DNA Tuned",
    notes: "Premium cushioned trainer with plush landings and a smoother, broader platform.",
  },
  {
    shoeSlug: "brooks-adrenaline-gts",
    versionName: "Adrenaline GTS 24",
    releaseYear: 2024,
    msrpUsd: "140.00",
    isCurrent: true,
    isPlated: false,
    foam: "DNA Loft v3",
    notes: "Structured daily trainer using GuideRails support for steady mileage.",
  },
  {
    shoeSlug: "brooks-cascadia",
    versionName: "Cascadia 17",
    releaseYear: 2023,
    msrpUsd: "140.00",
    isCurrent: false,
    isPlated: false,
    foam: "DNA Loft v2",
    notes: "Stable trail mileage with a protective ride and broad base for technical terrain.",
  },
  {
    shoeSlug: "brooks-cascadia",
    versionName: "Cascadia 18",
    releaseYear: 2024,
    msrpUsd: "140.00",
    isCurrent: true,
    isPlated: false,
    foam: "DNA Loft v2",
    notes: "Current Cascadia for durable trail training with predictable footing and protection.",
  },
  {
    shoeSlug: "asics-gel-nimbus",
    versionName: "GEL-Nimbus 26",
    releaseYear: 2024,
    msrpUsd: "160.00",
    isCurrent: false,
    isPlated: false,
    foam: "FF BLAST PLUS ECO",
    notes: "High-cushion road trainer with soft landings and an easy-mileage emphasis.",
  },
  {
    shoeSlug: "asics-gel-nimbus",
    versionName: "GEL-Nimbus 27",
    releaseYear: 2025,
    msrpUsd: "165.00",
    isCurrent: true,
    isPlated: false,
    foam: "FF BLAST PLUS",
    notes: "Soft max-cushion road trainer tuned for smooth daily mileage and long runs.",
  },
  {
    shoeSlug: "asics-novablast",
    versionName: "Novablast 5",
    releaseYear: 2024,
    msrpUsd: "150.00",
    isCurrent: true,
    isPlated: false,
    foam: "FF BLAST MAX",
    notes: "Bouncy trainer built around a lively toe-off and quicker daily running.",
  },
  {
    shoeSlug: "asics-gel-kayano",
    versionName: "GEL-Kayano 30",
    releaseYear: 2024,
    msrpUsd: "160.00",
    isCurrent: false,
    isPlated: false,
    foam: "FF BLAST PLUS ECO",
    notes: "Stable daily trainer with 4D guidance and a high-cushion, controlled platform.",
  },
  {
    shoeSlug: "asics-gel-kayano",
    versionName: "GEL-Kayano 31",
    releaseYear: 2025,
    msrpUsd: "165.00",
    isCurrent: true,
    isPlated: false,
    foam: "FF BLAST PLUS ECO",
    notes: "Current Kayano focused on guided comfort for daily and long mileage.",
  },
  {
    shoeSlug: "asics-superblast",
    versionName: "Superblast",
    releaseYear: 2023,
    msrpUsd: "200.00",
    isCurrent: false,
    isPlated: false,
    foam: "FF TURBO + FF BLAST PLUS",
    notes: "First-generation super trainer with broad appeal for long runs and steady workouts.",
  },
  {
    shoeSlug: "asics-superblast",
    versionName: "Superblast 2",
    releaseYear: 2024,
    msrpUsd: "200.00",
    isCurrent: true,
    isPlated: false,
    foam: "FF TURBO + FF BLAST PLUS ECO",
    notes: "Current super trainer with lighter feel and versatile high-stack road usage.",
  },
  {
    shoeSlug: "new-balance-1080",
    versionName: "Fresh Foam X 1080v13",
    releaseYear: 2023,
    msrpUsd: "164.99",
    isCurrent: false,
    isPlated: false,
    foam: "Fresh Foam X",
    notes: "Previous 1080 version centered on soft comfort and broad daily versatility.",
  },
  {
    shoeSlug: "new-balance-1080",
    versionName: "Fresh Foam X 1080v14",
    releaseYear: 2024,
    msrpUsd: "164.99",
    isCurrent: true,
    isPlated: false,
    foam: "Fresh Foam X",
    notes: "Current 1080 with a smoother rocker and extra-soft everyday road comfort.",
  },
  {
    shoeSlug: "new-balance-rebel",
    versionName: "FuelCell Rebel v3",
    releaseYear: 2023,
    msrpUsd: "140.00",
    isCurrent: false,
    isPlated: false,
    foam: "FuelCell",
    notes: "Light and flexible speed-oriented trainer with strong fan support for uptempo daily use.",
  },
  {
    shoeSlug: "new-balance-rebel",
    versionName: "FuelCell Rebel v4",
    releaseYear: 2024,
    msrpUsd: "140.00",
    isCurrent: true,
    isPlated: false,
    foam: "FuelCell",
    notes: "Current Rebel with more underfoot substance while keeping its lightweight fast-day identity.",
  },
  {
    shoeSlug: "new-balance-more",
    versionName: "Fresh Foam X More v4",
    releaseYear: 2023,
    msrpUsd: "150.00",
    isCurrent: false,
    isPlated: false,
    foam: "Fresh Foam X",
    notes: "Soft max-cushion mileage shoe built around easy-run comfort.",
  },
  {
    shoeSlug: "new-balance-more",
    versionName: "Fresh Foam X More v5",
    releaseYear: 2024,
    msrpUsd: "155.00",
    isCurrent: true,
    isPlated: false,
    foam: "Fresh Foam X",
    notes: "Current More with a broad, highly cushioned platform for easy and recovery mileage.",
  },
  {
    shoeSlug: "saucony-peregrine",
    versionName: "Peregrine 14",
    releaseYear: 2024,
    msrpUsd: "140.00",
    isCurrent: false,
    isPlated: false,
    foam: "PWRRUN",
    notes: "All-around trail shoe with solid grip and enough protection for varied surfaces.",
  },
  {
    shoeSlug: "saucony-peregrine",
    versionName: "Peregrine 15",
    releaseYear: 2025,
    msrpUsd: "145.00",
    isCurrent: true,
    isPlated: false,
    foam: "PWRRUN",
    notes: "Current Peregrine for adaptable trail mileage with strong underfoot confidence.",
  },
  {
    shoeSlug: "nike-pegasus-trail",
    versionName: "Pegasus Trail 4",
    releaseYear: 2023,
    msrpUsd: "150.00",
    isCurrent: false,
    isPlated: false,
    foam: "React",
    notes: "Road-to-trail crossover for runners who prioritize versatility over aggressive lugs.",
  },
  {
    shoeSlug: "nike-pegasus-trail",
    versionName: "Pegasus Trail 5",
    releaseYear: 2024,
    msrpUsd: "155.00",
    isCurrent: true,
    isPlated: false,
    foam: "ReactX",
    notes: "Current Pegasus Trail tuned for easier off-road miles and mixed-surface use.",
  },
  {
    shoeSlug: "asics-trabuco-max",
    versionName: "Trabuco Max 3",
    releaseYear: 2024,
    msrpUsd: "160.00",
    isCurrent: false,
    isPlated: false,
    foam: "FF BLAST PLUS ECO",
    notes: "High-stack trail cruiser designed for comfort and protection over long off-road runs.",
  },
  {
    shoeSlug: "asics-trabuco-max",
    versionName: "Trabuco Max 4",
    releaseYear: 2025,
    msrpUsd: "165.00",
    isCurrent: true,
    isPlated: false,
    foam: "FF BLAST PLUS ECO",
    notes: "Current max-cushion trail option with a rolling feel for ultra-style distances.",
  },
  {
    shoeSlug: "adidas-terrex-agravic-speed-ultra",
    versionName: "Terrex Agravic Speed Ultra",
    releaseYear: 2024,
    msrpUsd: "220.00",
    isCurrent: false,
    isPlated: true,
    foam: "Lightstrike Pro",
    notes: "Trail race shoe built for speed and cushioning over long off-road efforts.",
  },
  {
    shoeSlug: "adidas-terrex-agravic-speed-ultra",
    versionName: "Terrex Agravic Speed Ultra 2",
    releaseYear: 2025,
    msrpUsd: "220.00",
    isCurrent: true,
    isPlated: true,
    foam: "Lightstrike Pro",
    notes: "Current Terrex race option for mountain speed and long technical trail efforts.",
  },
  {
    shoeSlug: "salomon-speedcross",
    versionName: "Speedcross 5",
    releaseYear: 2023,
    msrpUsd: "140.00",
    isCurrent: false,
    isPlated: false,
    foam: "EnergyCell+",
    notes: "Legendary mud-focused trail shoe built around grip and foothold more than softness.",
  },
  {
    shoeSlug: "salomon-speedcross",
    versionName: "Speedcross 6",
    releaseYear: 2024,
    msrpUsd: "150.00",
    isCurrent: true,
    isPlated: false,
    foam: "EnergyCell+",
    notes: "Current Speedcross keeps the aggressive traction and secure upper that define the line.",
  },
  {
    shoeSlug: "hoka-clifton",
    versionName: "Clifton 9",
    releaseYear: 2023,
    msrpUsd: "145.00",
    isCurrent: false,
    isPlated: false,
    foam: "Compression-molded EVA",
    notes: "Earlier Clifton generation with broad appeal for moderate-cushion everyday road running.",
  },
  {
    shoeSlug: "hoka-clifton",
    versionName: "Clifton 10",
    releaseYear: 2025,
    msrpUsd: "155.00",
    isCurrent: true,
    isPlated: false,
    foam: "Compression-molded EVA",
    notes: "Current Clifton with a smoother rocker and slightly more substantial underfoot feel.",
  },
  {
    shoeSlug: "hoka-bondi",
    versionName: "Bondi 8",
    releaseYear: 2023,
    msrpUsd: "165.00",
    isCurrent: false,
    isPlated: false,
    foam: "EVA",
    notes: "Previous max-cushion Bondi known for protection and a broad easy-run audience.",
  },
  {
    shoeSlug: "hoka-bondi",
    versionName: "Bondi 9",
    releaseYear: 2025,
    msrpUsd: "175.00",
    isCurrent: true,
    isPlated: false,
    foam: "Super Critical EVA",
    notes: "Current Bondi with a softer premium feel for daily and recovery mileage.",
  },
  {
    shoeSlug: "hoka-cielo-x1",
    versionName: "Cielo X1",
    releaseYear: 2024,
    msrpUsd: "275.00",
    isCurrent: false,
    isPlated: true,
    foam: "PEBA",
    notes: "Aggressive high-stack carbon shoe positioned between racer and super trainer.",
  },
  {
    shoeSlug: "hoka-cielo-x1",
    versionName: "Cielo X1 2.0",
    releaseYear: 2025,
    msrpUsd: "275.00",
    isCurrent: true,
    isPlated: true,
    foam: "PEBA",
    notes: "Refined current version of HOKA's high-stack carbon offering for faster road sessions.",
  },
  {
    shoeSlug: "hoka-speedgoat",
    versionName: "Speedgoat 5",
    releaseYear: 2023,
    msrpUsd: "155.00",
    isCurrent: false,
    isPlated: false,
    foam: "CMEVA",
    notes: "Popular technical-trail shoe with strong grip and cushioned protection for long off-road days.",
  },
  {
    shoeSlug: "hoka-speedgoat",
    versionName: "Speedgoat 6",
    releaseYear: 2024,
    msrpUsd: "155.00",
    isCurrent: true,
    isPlated: false,
    foam: "CMEVA",
    notes: "Current Speedgoat balancing traction, cushioning, and mountain-ready protection.",
  },
  {
    shoeSlug: "altra-torin",
    versionName: "Torin 7",
    releaseYear: 2023,
    msrpUsd: "150.00",
    isCurrent: false,
    isPlated: false,
    foam: "EGO MAX",
    notes: "Zero-drop daily trainer with a roomy forefoot and a softer training profile.",
  },
  {
    shoeSlug: "altra-torin",
    versionName: "Torin 8",
    releaseYear: 2024,
    msrpUsd: "150.00",
    isCurrent: true,
    isPlated: false,
    foam: "EGO MAX",
    notes: "Current Torin focused on easy road mileage within Altra's natural-footshape platform.",
  },
  {
    shoeSlug: "altra-lone-peak",
    versionName: "Lone Peak 8",
    releaseYear: 2024,
    msrpUsd: "140.00",
    isCurrent: false,
    isPlated: false,
    foam: "EGO",
    notes: "Popular trail mileage shoe with grip, room up front, and a loyal hiking-running crossover audience.",
  },
  {
    shoeSlug: "altra-lone-peak",
    versionName: "Lone Peak 9",
    releaseYear: 2025,
    msrpUsd: "145.00",
    isCurrent: true,
    isPlated: false,
    foam: "EGO",
    notes: "Current Lone Peak for trail mileage and fastpacking with a familiar zero-drop stance.",
  },
  {
    shoeSlug: "altra-vanish-carbon",
    versionName: "Vanish Carbon",
    releaseYear: 2023,
    msrpUsd: "240.00",
    isCurrent: false,
    isPlated: true,
    foam: "EGO PRO",
    notes: "First carbon race model in Altra's road lineup, carrying zero-drop geometry into race use.",
  },
  {
    shoeSlug: "altra-vanish-carbon",
    versionName: "Vanish Carbon 2",
    releaseYear: 2025,
    msrpUsd: "260.00",
    isCurrent: true,
    isPlated: true,
    foam: "EGO PRO",
    notes: "Current Altra race shoe with zero-drop geometry and a firmer, fast-day carbon feel.",
  },
  {
    shoeSlug: "mizuno-wave-rider",
    versionName: "Wave Rider 27",
    releaseYear: 2023,
    msrpUsd: "140.00",
    isCurrent: false,
    isPlated: false,
    foam: "MIZUNO ENERZY",
    notes: "Traditional neutral mileage shoe with a smooth, moderately firm ride.",
  },
  {
    shoeSlug: "mizuno-wave-rider",
    versionName: "Wave Rider 28",
    releaseYear: 2024,
    msrpUsd: "145.00",
    isCurrent: true,
    isPlated: false,
    foam: "MIZUNO ENERZY NXT",
    notes: "Current Wave Rider keeping the line's reliable daily-run identity with a little more softness.",
  },
  {
    shoeSlug: "mizuno-wave-sky",
    versionName: "Wave Sky 7",
    releaseYear: 2023,
    msrpUsd: "170.00",
    isCurrent: false,
    isPlated: false,
    foam: "MIZUNO ENERZY",
    notes: "Premium cushioned mileage designed for smooth long runs and easy comfort.",
  },
  {
    shoeSlug: "mizuno-wave-sky",
    versionName: "Wave Sky 8",
    releaseYear: 2024,
    msrpUsd: "175.00",
    isCurrent: true,
    isPlated: false,
    foam: "MIZUNO ENERZY NXT",
    notes: "Current premium cushioned Mizuno road option for easy and long mileage.",
  },
  {
    shoeSlug: "puma-deviate-nitro",
    versionName: "Deviate NITRO 2",
    releaseYear: 2023,
    msrpUsd: "160.00",
    isCurrent: false,
    isPlated: true,
    foam: "NITROFOAM",
    notes: "Earlier plated trainer that helped establish PUMA's fast-day road identity.",
  },
  {
    shoeSlug: "puma-deviate-nitro",
    versionName: "Deviate NITRO 3",
    releaseYear: 2024,
    msrpUsd: "160.00",
    isCurrent: true,
    isPlated: true,
    foam: "NITROFOAM",
    notes: "Current plated trainer with snappy propulsion for workouts and fast long runs.",
  },
  {
    shoeSlug: "puma-velocity-nitro",
    versionName: "Velocity NITRO 2",
    releaseYear: 2023,
    msrpUsd: "135.00",
    isCurrent: false,
    isPlated: false,
    foam: "NITROFOAM",
    notes: "Versatile daily neutral trainer with a lively but approachable ride.",
  },
  {
    shoeSlug: "puma-velocity-nitro",
    versionName: "Velocity NITRO 3",
    releaseYear: 2024,
    msrpUsd: "140.00",
    isCurrent: true,
    isPlated: false,
    foam: "NITROFOAM",
    notes: "Current everyday PUMA trainer balancing comfort, durability, and a bit of pop.",
  },
  {
    shoeSlug: "adidas-adizero-boston",
    versionName: "Adizero Boston 12",
    releaseYear: 2024,
    msrpUsd: "160.00",
    isCurrent: false,
    isPlated: true,
    foam: "Lightstrike Pro",
    notes: "Earlier Boston version with race-line geometry built for harder training sessions.",
  },
  {
    shoeSlug: "adidas-adizero-boston",
    versionName: "Adizero Boston 13",
    releaseYear: 2025,
    msrpUsd: "160.00",
    isCurrent: true,
    isPlated: true,
    foam: "Lightstrike Pro",
    notes: "Current Boston emphasizing long workout mileage and firmer road efficiency.",
  },
  {
    shoeSlug: "adidas-adizero-adios-pro",
    versionName: "Adizero Adios Pro 3",
    releaseYear: 2023,
    msrpUsd: "250.00",
    isCurrent: false,
    isPlated: true,
    foam: "Lightstrike Pro",
    notes: "Previous flagship marathon racer with a strong reputation for race-day efficiency.",
  },
  {
    shoeSlug: "adidas-adizero-adios-pro",
    versionName: "Adizero Adios Pro 4",
    releaseYear: 2025,
    msrpUsd: "250.00",
    isCurrent: true,
    isPlated: true,
    foam: "Lightstrike Pro",
    notes: "Current flagship Adidas road racer for marathon-focused performance.",
  },
  {
    shoeSlug: "salomon-aero-glide",
    versionName: "Aero Glide 2",
    releaseYear: 2024,
    msrpUsd: "160.00",
    isCurrent: false,
    isPlated: false,
    foam: "Energy Foam",
    notes: "Road max-cushion trainer with a secure upper and smooth transition focus.",
  },
  {
    shoeSlug: "salomon-aero-glide",
    versionName: "Aero Glide 3",
    releaseYear: 2025,
    msrpUsd: "160.00",
    isCurrent: true,
    isPlated: false,
    foam: "Energy Foam evo",
    notes: "Current Salomon road mileage option with more cushion and easier long-run comfort.",
  },
];

export const seedSpecs: SeedSpec[] = [
  {
    releaseKey: "nike-pegasus:Pegasus 40",
    weightOzMen: "9.4",
    heelStackMm: 36,
    forefootStackMm: 26,
    dropMm: 10,
    fitNotes: "Classic Pegasus fit with moderate forefoot room and easy sizing for most runners.",
  },
  {
    releaseKey: "nike-pegasus:Pegasus 41",
    weightOzMen: "9.9",
    heelStackMm: 37,
    forefootStackMm: 27,
    dropMm: 10,
    fitNotes: "True to size for most runners, medium forefoot volume.",
  },
  {
    releaseKey: "nike-vomero:Vomero 18",
    weightOzMen: "11.5",
    heelStackMm: 46,
    forefootStackMm: 36,
    dropMm: 10,
    fitNotes: "Plush upper with broad everyday comfort and a more substantial fit than Pegasus.",
  },
  {
    releaseKey: "nike-alphafly:Alphafly 3",
    weightOzMen: "7.7",
    heelStackMm: 40,
    forefootStackMm: 32,
    dropMm: 8,
    fitNotes: "Race-day fit with a secure midfoot and a more dialed-in forefoot than max trainers.",
  },
  {
    releaseKey: "saucony-endorphin-speed:Endorphin Speed 3",
    weightOzMen: "8.1",
    heelStackMm: 36,
    forefootStackMm: 28,
    dropMm: 8,
    fitNotes: "Performance-oriented upper with secure heel hold and moderate forefoot width.",
  },
  {
    releaseKey: "saucony-endorphin-speed:Endorphin Speed 4",
    weightOzMen: "8.2",
    heelStackMm: 36,
    forefootStackMm: 28,
    dropMm: 8,
    fitNotes: "Performance fit with secure midfoot and moderate toe box width.",
  },
  {
    releaseKey: "saucony-triumph:Triumph 21",
    weightOzMen: "9.8",
    heelStackMm: 37,
    forefootStackMm: 27,
    dropMm: 10,
    fitNotes: "Roomy daily-trainer fit with solid heel hold and long-run comfort focus.",
  },
  {
    releaseKey: "saucony-triumph:Triumph 22",
    weightOzMen: "10.1",
    heelStackMm: 37,
    forefootStackMm: 27,
    dropMm: 10,
    fitNotes: "Premium upper and softer platform make this one comfortable without feeling sloppy.",
  },
  {
    releaseKey: "saucony-ride:Ride 17",
    weightOzMen: "9.4",
    heelStackMm: 35,
    forefootStackMm: 27,
    dropMm: 8,
    fitNotes: "Straightforward neutral fit with enough space for daily miles and all-day wear.",
  },
  {
    releaseKey: "saucony-ride:Ride 18",
    weightOzMen: "9.1",
    heelStackMm: 35,
    forefootStackMm: 27,
    dropMm: 8,
    fitNotes: "Easy, adaptable fit with enough room for regular training and casual wear overlap.",
  },
  {
    releaseKey: "saucony-guide:Guide 18",
    weightOzMen: "9.6",
    heelStackMm: 35,
    forefootStackMm: 29,
    dropMm: 6,
    fitNotes: "Secure heel and broad base underfoot create a stable, protected daily fit.",
  },
  {
    releaseKey: "hoka-mach:Mach 5",
    weightOzMen: "8.3",
    heelStackMm: 29,
    forefootStackMm: 24,
    dropMm: 5,
    fitNotes: "Sleek upper and moderate toe box keep the fit performance-oriented but not harsh.",
  },
  {
    releaseKey: "hoka-mach:Mach 6",
    weightOzMen: "8.2",
    heelStackMm: 37,
    forefootStackMm: 32,
    dropMm: 5,
    fitNotes: "Sleeker upper than classic max-cushion Hokas, medium width overall.",
  },
  {
    releaseKey: "brooks-ghost:Ghost 16",
    weightOzMen: "9.5",
    heelStackMm: 36,
    forefootStackMm: 24,
    dropMm: 12,
    fitNotes: "Classic Brooks daily fit with broad appeal, especially for heel strikers.",
  },
  {
    releaseKey: "brooks-ghost:Ghost 17",
    weightOzMen: "10.1",
    heelStackMm: 37,
    forefootStackMm: 27,
    dropMm: 10,
    fitNotes: "Comfortable neutral fit with a familiar Brooks shape and a little more cushioning than Ghost 16.",
  },
  {
    releaseKey: "brooks-glycerin:Glycerin 22",
    weightOzMen: "10.2",
    heelStackMm: 38,
    forefootStackMm: 28,
    dropMm: 10,
    fitNotes: "Premium upper and broad platform create a plush fit for long easy runs.",
  },
  {
    releaseKey: "brooks-adrenaline-gts:Adrenaline GTS 24",
    weightOzMen: "10.1",
    heelStackMm: 36,
    forefootStackMm: 24,
    dropMm: 12,
    fitNotes: "Structured feel with Brooks' familiar fit profile and easy transition into daily support use.",
  },
  {
    releaseKey: "asics-gel-nimbus:GEL-Nimbus 26",
    weightOzMen: "10.7",
    heelStackMm: 42,
    forefootStackMm: 34,
    dropMm: 8,
    fitNotes: "Soft, padded upper with a premium daily-training fit and strong long-run comfort.",
  },
  {
    releaseKey: "asics-gel-nimbus:GEL-Nimbus 27",
    weightOzMen: "9.3",
    heelStackMm: 44,
    forefootStackMm: 36,
    dropMm: 8,
    fitNotes: "Very cushioned, soft-fitting upper with plenty of comfort for easy road mileage.",
  },
  {
    releaseKey: "asics-novablast:Novablast 5",
    weightOzMen: "9.0",
    heelStackMm: 42,
    forefootStackMm: 34,
    dropMm: 8,
    fitNotes: "Flexible upper with a comfortable midfoot hold and room for faster daily efforts.",
  },
  {
    releaseKey: "asics-gel-kayano:GEL-Kayano 30",
    weightOzMen: "10.7",
    heelStackMm: 40,
    forefootStackMm: 30,
    dropMm: 10,
    fitNotes: "Supportive daily fit with a broad, stable platform and padded upper feel.",
  },
  {
    releaseKey: "asics-gel-kayano:GEL-Kayano 31",
    weightOzMen: "10.8",
    heelStackMm: 40,
    forefootStackMm: 30,
    dropMm: 10,
    fitNotes: "Secure support fit with stable geometry and plenty of long-run comfort.",
  },
  {
    releaseKey: "asics-superblast:Superblast",
    weightOzMen: "8.4",
    heelStackMm: 45,
    forefootStackMm: 37,
    dropMm: 8,
    fitNotes: "High-stack fit with a race-inspired feel but enough room for daily long-run use.",
  },
  {
    releaseKey: "asics-superblast:Superblast 2",
    weightOzMen: "8.8",
    heelStackMm: 45,
    forefootStackMm: 37,
    dropMm: 8,
    fitNotes: "Secure high-stack training fit that still feels lighter than its size suggests.",
  },
  {
    releaseKey: "new-balance-1080:Fresh Foam X 1080v13",
    weightOzMen: "9.3",
    heelStackMm: 38,
    forefootStackMm: 32,
    dropMm: 6,
    fitNotes: "Soft upper and balanced toe box make it easy to wear for long easy days.",
  },
  {
    releaseKey: "new-balance-1080:Fresh Foam X 1080v14",
    weightOzMen: "10.5",
    heelStackMm: 38,
    forefootStackMm: 32,
    dropMm: 6,
    fitNotes: "Smooth rocker and forgiving upper create an easygoing fit for everyday miles.",
  },
  {
    releaseKey: "new-balance-rebel:FuelCell Rebel v3",
    weightOzMen: "7.4",
    heelStackMm: 33,
    forefootStackMm: 27,
    dropMm: 6,
    fitNotes: "Light and agile fit with enough room for tempo days but a more performance-led shape.",
  },
  {
    releaseKey: "new-balance-rebel:FuelCell Rebel v4",
    weightOzMen: "7.8",
    heelStackMm: 34,
    forefootStackMm: 28,
    dropMm: 6,
    fitNotes: "Fast-day fit with a little more underfoot substance and broader daily usability.",
  },
  {
    releaseKey: "new-balance-more:Fresh Foam X More v4",
    weightOzMen: "10.4",
    heelStackMm: 40,
    forefootStackMm: 36,
    dropMm: 4,
    fitNotes: "Soft, roomy fit and a broad platform make it easy to use for recovery and long easy runs.",
  },
  {
    releaseKey: "new-balance-more:Fresh Foam X More v5",
    weightOzMen: "10.6",
    heelStackMm: 44,
    forefootStackMm: 40,
    dropMm: 4,
    fitNotes: "Very cushioned and spacious underfoot, aimed squarely at comfort-focused mileage.",
  },
  {
    releaseKey: "saucony-peregrine:Peregrine 14",
    weightOzMen: "9.5",
    heelStackMm: 28,
    forefootStackMm: 24,
    dropMm: 4,
    fitNotes: "Trail fit with secure hold and enough protection for daily off-road use.",
  },
  {
    releaseKey: "saucony-peregrine:Peregrine 15",
    weightOzMen: "9.4",
    heelStackMm: 28,
    forefootStackMm: 24,
    dropMm: 4,
    fitNotes: "Current Peregrine fit balances trail hold with enough room for longer runs and hiking crossover.",
  },
  {
    releaseKey: "nike-pegasus-trail:Pegasus Trail 4",
    weightOzMen: "10.4",
    heelStackMm: 36,
    forefootStackMm: 26,
    dropMm: 10,
    fitNotes: "Road-oriented fit with enough outsole grip for lighter trail and gravel mileage.",
  },
  {
    releaseKey: "nike-pegasus-trail:Pegasus Trail 5",
    weightOzMen: "10.0",
    heelStackMm: 37,
    forefootStackMm: 27,
    dropMm: 10,
    fitNotes: "Current mixed-surface fit keeps the Pegasus feel while adding trail-ready confidence.",
  },
  {
    releaseKey: "asics-trabuco-max:Trabuco Max 3",
    weightOzMen: "10.8",
    heelStackMm: 42,
    forefootStackMm: 37,
    dropMm: 5,
    fitNotes: "Plush trail fit with strong protection and a geometry built for long rolling miles.",
  },
  {
    releaseKey: "asics-trabuco-max:Trabuco Max 4",
    weightOzMen: "10.7",
    heelStackMm: 43,
    forefootStackMm: 38,
    dropMm: 5,
    fitNotes: "Current max-cushion trail fit with a broad base and secure upper for long-distance trail comfort.",
  },
  {
    releaseKey: "hoka-speedgoat:Speedgoat 5",
    weightOzMen: "10.3",
    heelStackMm: 33,
    forefootStackMm: 29,
    dropMm: 4,
    fitNotes: "Trail-specific fit with good foothold and enough room for long mountain runs.",
  },
  {
    releaseKey: "hoka-speedgoat:Speedgoat 6",
    weightOzMen: "9.8",
    heelStackMm: 40,
    forefootStackMm: 35,
    dropMm: 5,
    fitNotes: "Current Speedgoat keeps a secure trail fit with strong foothold over technical terrain.",
  },
  {
    releaseKey: "brooks-cascadia:Cascadia 17",
    weightOzMen: "11.1",
    heelStackMm: 34,
    forefootStackMm: 26,
    dropMm: 8,
    fitNotes: "Stable trail fit with a secure midfoot and enough upper structure for technical terrain.",
  },
  {
    releaseKey: "brooks-cascadia:Cascadia 18",
    weightOzMen: "11.2",
    heelStackMm: 35,
    forefootStackMm: 27,
    dropMm: 8,
    fitNotes: "Current Cascadia stays secure and planted for runners who want predictable trail support.",
  },
  {
    releaseKey: "adidas-terrex-agravic-speed-ultra:Terrex Agravic Speed Ultra",
    weightOzMen: "9.6",
    heelStackMm: 38,
    forefootStackMm: 30,
    dropMm: 8,
    fitNotes: "Trail-race fit with a secure upper and firmer fast-day underfoot feel.",
  },
  {
    releaseKey: "adidas-terrex-agravic-speed-ultra:Terrex Agravic Speed Ultra 2",
    weightOzMen: "9.4",
    heelStackMm: 38,
    forefootStackMm: 30,
    dropMm: 8,
    fitNotes: "Current race-focused trail fit built for speed, grip, and control over longer efforts.",
  },
  {
    releaseKey: "salomon-speedcross:Speedcross 5",
    weightOzMen: "11.5",
    heelStackMm: 30,
    forefootStackMm: 20,
    dropMm: 10,
    fitNotes: "Snug, trail-specific foothold built for grip, mud, and secure descending.",
  },
  {
    releaseKey: "salomon-speedcross:Speedcross 6",
    weightOzMen: "12.0",
    heelStackMm: 32,
    forefootStackMm: 22,
    dropMm: 10,
    fitNotes: "Current Speedcross fit stays narrow and locked in for muddy, technical trail usage.",
  },
  {
    releaseKey: "hoka-clifton:Clifton 9",
    weightOzMen: "8.7",
    heelStackMm: 32,
    forefootStackMm: 27,
    dropMm: 5,
    fitNotes: "Slimmer HOKA fit with moderate cushioning and easy daily-run versatility.",
  },
  {
    releaseKey: "hoka-clifton:Clifton 10",
    weightOzMen: "9.8",
    heelStackMm: 42,
    forefootStackMm: 34,
    dropMm: 8,
    fitNotes: "More substantial than older Cliftons but still streamlined for daily road use.",
  },
  {
    releaseKey: "hoka-bondi:Bondi 8",
    weightOzMen: "10.8",
    heelStackMm: 39,
    forefootStackMm: 35,
    dropMm: 4,
    fitNotes: "Max-cushion fit with abundant padding and a highly protective everyday feel.",
  },
  {
    releaseKey: "hoka-bondi:Bondi 9",
    weightOzMen: "10.5",
    heelStackMm: 43,
    forefootStackMm: 38,
    dropMm: 5,
    fitNotes: "Plush, protective road fit for recovery and easy mileage with noticeable underfoot volume.",
  },
  {
    releaseKey: "hoka-cielo-x1:Cielo X1",
    weightOzMen: "9.3",
    heelStackMm: 48,
    forefootStackMm: 41,
    dropMm: 7,
    fitNotes: "Race-oriented fit with a high-stack aggressive feel and a more dialed-in hold.",
  },
  {
    releaseKey: "hoka-cielo-x1:Cielo X1 2.0",
    weightOzMen: "8.1",
    heelStackMm: 47,
    forefootStackMm: 40,
    dropMm: 7,
    fitNotes: "Fast, race-day fit with a bit more refinement and less bulk than the first version.",
  },
  {
    releaseKey: "altra-torin:Torin 7",
    weightOzMen: "9.8",
    heelStackMm: 30,
    forefootStackMm: 30,
    dropMm: 0,
    fitNotes: "Foot-shaped fit with zero-drop geometry and broad forefoot comfort for everyday mileage.",
  },
  {
    releaseKey: "altra-torin:Torin 8",
    weightOzMen: "9.5",
    heelStackMm: 30,
    forefootStackMm: 30,
    dropMm: 0,
    fitNotes: "Current Torin keeps the roomy forefoot and natural stance that define Altra road mileage.",
  },
  {
    releaseKey: "altra-lone-peak:Lone Peak 8",
    weightOzMen: "10.6",
    heelStackMm: 25,
    forefootStackMm: 25,
    dropMm: 0,
    fitNotes: "Trail-specific fit with toe-box room and a secure enough hold for long off-road days.",
  },
  {
    releaseKey: "altra-lone-peak:Lone Peak 9",
    weightOzMen: "11.0",
    heelStackMm: 25,
    forefootStackMm: 25,
    dropMm: 0,
    fitNotes: "Current Lone Peak preserves the roomy Altra trail fit and zero-drop stance.",
  },
  {
    releaseKey: "altra-vanish-carbon:Vanish Carbon",
    weightOzMen: "7.5",
    heelStackMm: 33,
    forefootStackMm: 33,
    dropMm: 0,
    fitNotes: "Race-focused zero-drop fit with a snugger midfoot and high-efficiency forefoot feel.",
  },
  {
    releaseKey: "altra-vanish-carbon:Vanish Carbon 2",
    weightOzMen: "7.3",
    heelStackMm: 33,
    forefootStackMm: 33,
    dropMm: 0,
    fitNotes: "Current Altra race fit stays narrow enough for performance while keeping a foot-shaped forefoot.",
  },
  {
    releaseKey: "mizuno-wave-rider:Wave Rider 27",
    weightOzMen: "10.1",
    heelStackMm: 38,
    forefootStackMm: 26,
    dropMm: 12,
    fitNotes: "Traditional daily-training fit with secure heel hold and a classic Mizuno shape.",
  },
  {
    releaseKey: "mizuno-wave-rider:Wave Rider 28",
    weightOzMen: "10.4",
    heelStackMm: 39,
    forefootStackMm: 27,
    dropMm: 12,
    fitNotes: "Reliable training fit for runners who like a more structured, traditional road shoe feel.",
  },
  {
    releaseKey: "mizuno-wave-sky:Wave Sky 7",
    weightOzMen: "10.5",
    heelStackMm: 41,
    forefootStackMm: 33,
    dropMm: 8,
    fitNotes: "Premium padded fit with long-run comfort and more structure than softer max trainers.",
  },
  {
    releaseKey: "mizuno-wave-sky:Wave Sky 8",
    weightOzMen: "10.7",
    heelStackMm: 42,
    forefootStackMm: 34,
    dropMm: 8,
    fitNotes: "Current Wave Sky feels cushioned but still traditionally structured underfoot.",
  },
  {
    releaseKey: "puma-deviate-nitro:Deviate NITRO 2",
    weightOzMen: "9.4",
    heelStackMm: 39,
    forefootStackMm: 29,
    dropMm: 10,
    fitNotes: "Secure plated training fit with a race-adjacent feel for faster sessions.",
  },
  {
    releaseKey: "puma-deviate-nitro:Deviate NITRO 3",
    weightOzMen: "9.1",
    heelStackMm: 39,
    forefootStackMm: 29,
    dropMm: 10,
    fitNotes: "Current plated workout fit with a stable enough platform for longer faster efforts.",
  },
  {
    releaseKey: "puma-velocity-nitro:Velocity NITRO 2",
    weightOzMen: "9.2",
    heelStackMm: 38,
    forefootStackMm: 28,
    dropMm: 10,
    fitNotes: "Versatile neutral fit that works well for everyday training and walking around after runs.",
  },
  {
    releaseKey: "puma-velocity-nitro:Velocity NITRO 3",
    weightOzMen: "9.4",
    heelStackMm: 39,
    forefootStackMm: 29,
    dropMm: 10,
    fitNotes: "Current everyday PUMA fit with a balanced shape and easy all-around use.",
  },
  {
    releaseKey: "adidas-adizero-boston:Adizero Boston 12",
    weightOzMen: "9.5",
    heelStackMm: 38,
    forefootStackMm: 32,
    dropMm: 6,
    fitNotes: "Workout-focused fit with firmer underfoot feel and race-line geometry.",
  },
  {
    releaseKey: "adidas-adizero-boston:Adizero Boston 13",
    weightOzMen: "9.3",
    heelStackMm: 38,
    forefootStackMm: 32,
    dropMm: 6,
    fitNotes: "Current Boston stays firm and efficient for runners who like a more aggressive trainer shape.",
  },
  {
    releaseKey: "adidas-adizero-adios-pro:Adizero Adios Pro 3",
    weightOzMen: "7.8",
    heelStackMm: 39,
    forefootStackMm: 33,
    dropMm: 6,
    fitNotes: "Race fit with aggressive geometry and strong marathon-oriented energy return.",
  },
  {
    releaseKey: "adidas-adizero-adios-pro:Adizero Adios Pro 4",
    weightOzMen: "7.1",
    heelStackMm: 39,
    forefootStackMm: 33,
    dropMm: 6,
    fitNotes: "Current elite race fit with a lightweight, high-stack feel for goal-pace road racing.",
  },
  {
    releaseKey: "salomon-aero-glide:Aero Glide 2",
    weightOzMen: "9.8",
    heelStackMm: 41,
    forefootStackMm: 33,
    dropMm: 8,
    fitNotes: "Secure upper and high-cushion feel bring Salomon's snug road fit into easy mileage.",
  },
  {
    releaseKey: "salomon-aero-glide:Aero Glide 3",
    weightOzMen: "9.9",
    heelStackMm: 41,
    forefootStackMm: 33,
    dropMm: 8,
    fitNotes: "Current road mileage fit with plush cushioning and a supportive upper wrap.",
  },
];

export const seedReviewSources: SeedReviewSource[] = [
  {
    name: "RoadTrailRun",
    slug: "roadtrailrun",
    sourceType: "editorial",
    siteUrl: "https://www.roadtrailrun.com",
    baseDomain: "roadtrailrun.com",
  },
  {
    name: "Believe in the Run",
    slug: "believe-in-the-run",
    sourceType: "editorial",
    siteUrl: "https://believeintherun.com",
    baseDomain: "believeintherun.com",
  },
  {
    name: "r/RunningShoeGeeks",
    slug: "reddit-running-shoe-geeks",
    sourceType: "reddit",
    siteUrl: "https://www.reddit.com/r/RunningShoeGeeks/",
    baseDomain: "reddit.com",
  },
  {
    name: "RunRepeat",
    slug: "runrepeat",
    sourceType: "editorial",
    siteUrl: "https://runrepeat.com",
    baseDomain: "runrepeat.com",
  },
  {
    name: "Doctors of Running",
    slug: "doctors-of-running",
    sourceType: "editorial",
    siteUrl: "https://www.doctorsofrunning.com",
    baseDomain: "doctorsofrunning.com",
  },
];

export const seedReviewAuthors: SeedReviewAuthor[] = [
  {
    sourceSlug: "roadtrailrun",
    displayName: "RTR Editorial",
    profileUrl: "https://www.roadtrailrun.com",
  },
  {
    sourceSlug: "believe-in-the-run",
    displayName: "BITR Team",
    profileUrl: "https://believeintherun.com",
  },
  {
    sourceSlug: "reddit-running-shoe-geeks",
    displayName: "strideforum",
    profileUrl: "https://www.reddit.com/user/strideforum/",
  },
  {
    sourceSlug: "runrepeat",
    displayName: "RunRepeat Editorial",
    profileUrl: "https://runrepeat.com",
  },
  {
    sourceSlug: "doctors-of-running",
    displayName: "Doctors of Running",
    profileUrl: "https://www.doctorsofrunning.com",
  },
];

export const seedReviews: SeedReview[] = [
  {
    releaseKey: "nike-pegasus:Pegasus 40",
    sourceSlug: "reddit-running-shoe-geeks",
    authorName: "strideforum",
    sourceUrl: "https://example.com/reviews/nike-pegasus-40-reddit-thread",
    title: "Pegasus 40 remains a safe pick for everyday road mileage",
    excerpt:
      "Community sentiment leans positive on durability and familiarity, with more mixed comments on excitement compared to newer super-trainers.",
    scoreNormalized100: 76,
    originalScoreValue: "7.6",
    originalScoreScale: "10",
    sentiment: "mixed",
    status: "approved",
    publishedAt: "2024-01-08T00:00:00.000Z",
  },
  {
    releaseKey: "nike-pegasus:Pegasus 41",
    sourceSlug: "roadtrailrun",
    authorName: "RTR Editorial",
    sourceUrl: "https://example.com/reviews/nike-pegasus-41-rtr",
    title: "Pegasus 41 stays dependable for daily mileage",
    excerpt:
      "Reviewers liked the familiarity and durability, while noting it does not chase the super-trainer trend.",
    scoreNormalized100: 82,
    originalScoreValue: "8.2",
    originalScoreScale: "10",
    sentiment: "positive",
    status: "approved",
    publishedAt: "2024-06-10T00:00:00.000Z",
  },
  {
    releaseKey: "nike-vomero:Vomero 18",
    sourceSlug: "doctors-of-running",
    authorName: "Doctors of Running",
    sourceUrl: "https://example.com/reviews/nike-vomero-18-dor",
    title: "Vomero 18 leans all the way into max-cushion comfort",
    excerpt:
      "Reviewers praise the protective ride and easy-run comfort, with some caution that the shoe is heavy for faster work.",
    scoreNormalized100: 86,
    originalScoreValue: "8.6",
    originalScoreScale: "10",
    sentiment: "positive",
    status: "approved",
    publishedAt: "2025-02-14T00:00:00.000Z",
  },
  {
    releaseKey: "nike-alphafly:Alphafly 3",
    sourceSlug: "runrepeat",
    authorName: "RunRepeat Editorial",
    sourceUrl: "https://example.com/reviews/nike-alphafly-3-runrepeat",
    title: "Alphafly 3 is still one of the sharpest race-day tools",
    excerpt:
      "Coverage remains strongly positive on efficiency and turnover, though fit and stability comments are more selective than daily trainers.",
    scoreNormalized100: 94,
    originalScoreValue: "9.4",
    originalScoreScale: "10",
    sentiment: "positive",
    status: "approved",
    publishedAt: "2025-01-10T00:00:00.000Z",
  },
  {
    releaseKey: "saucony-endorphin-speed:Endorphin Speed 3",
    sourceSlug: "reddit-running-shoe-geeks",
    authorName: "strideforum",
    sourceUrl: "https://example.com/reviews/endorphin-speed-3-reddit-thread",
    title: "Endorphin Speed 3 stayed a community favorite for mixed training",
    excerpt:
      "Users consistently liked the versatility, with only occasional complaints about upper fit and late-run stability.",
    scoreNormalized100: 88,
    originalScoreValue: "8.8",
    originalScoreScale: "10",
    sentiment: "positive",
    status: "approved",
    publishedAt: "2024-02-22T00:00:00.000Z",
  },
  {
    releaseKey: "saucony-endorphin-speed:Endorphin Speed 4",
    sourceSlug: "believe-in-the-run",
    authorName: "BITR Team",
    sourceUrl: "https://example.com/reviews/endorphin-speed-4-bitr",
    title: "Endorphin Speed 4 remains the versatile fast trainer pick",
    excerpt:
      "The plate and foam combination continues to make it an all-purpose option for tempo work and long runs.",
    scoreNormalized100: 91,
    originalScoreValue: "9.1",
    originalScoreScale: "10",
    sentiment: "positive",
    status: "approved",
    publishedAt: "2024-03-04T00:00:00.000Z",
  },
  {
    releaseKey: "saucony-triumph:Triumph 22",
    sourceSlug: "roadtrailrun",
    authorName: "RTR Editorial",
    sourceUrl: "https://example.com/reviews/saucony-triumph-22-rtr",
    title: "Triumph 22 goes softer and bouncier without losing premium comfort",
    excerpt:
      "Editorial reviews like the update in underfoot feel, though some note it is less traditional than earlier Triumph versions.",
    scoreNormalized100: 87,
    originalScoreValue: "8.7",
    originalScoreScale: "10",
    sentiment: "positive",
    status: "approved",
    publishedAt: "2024-08-03T00:00:00.000Z",
  },
  {
    releaseKey: "saucony-ride:Ride 18",
    sourceSlug: "runrepeat",
    authorName: "RunRepeat Editorial",
    sourceUrl: "https://example.com/reviews/saucony-ride-18-runrepeat",
    title: "Ride 18 looks like a stronger all-around daily trainer than Ride 17",
    excerpt:
      "The lighter foam and smoother transition are consistent positives, while the shoe is still framed as more practical than flashy.",
    scoreNormalized100: 84,
    originalScoreValue: "8.4",
    originalScoreScale: "10",
    sentiment: "positive",
    status: "approved",
    publishedAt: "2025-01-29T00:00:00.000Z",
  },
  {
    releaseKey: "saucony-guide:Guide 18",
    sourceSlug: "doctors-of-running",
    authorName: "Doctors of Running",
    sourceUrl: "https://example.com/reviews/saucony-guide-18-dor",
    title: "Guide 18 gets credit for stable comfort without harsh posting",
    excerpt:
      "Support-focused reviewers like the broad base and controlled ride, with moderate notes on weight relative to neutral trainers.",
    scoreNormalized100: 83,
    originalScoreValue: "8.3",
    originalScoreScale: "10",
    sentiment: "positive",
    status: "approved",
    publishedAt: "2025-02-05T00:00:00.000Z",
  },
  {
    releaseKey: "hoka-mach:Mach 5",
    sourceSlug: "roadtrailrun",
    authorName: "RTR Editorial",
    sourceUrl: "https://example.com/reviews/hoka-mach-5-rtr",
    title: "Mach 5 stayed a favorite for lightweight everyday uptempo running",
    excerpt:
      "Reviewers liked its quick turnover and low-friction ride, with durability mentioned as the main caution.",
    scoreNormalized100: 85,
    originalScoreValue: "8.5",
    originalScoreScale: "10",
    sentiment: "positive",
    status: "approved",
    publishedAt: "2024-01-17T00:00:00.000Z",
  },
  {
    releaseKey: "hoka-mach:Mach 6",
    sourceSlug: "reddit-running-shoe-geeks",
    authorName: "strideforum",
    sourceUrl: "https://example.com/reviews/hoka-mach-6-reddit-thread",
    title: "Mach 6 gets praise for turnover but mixed comments on long-run comfort",
    excerpt:
      "Community feedback trends positive on pace changes, with more split opinions once runs get longer.",
    scoreNormalized100: 78,
    originalScoreValue: "7.8",
    originalScoreScale: "10",
    sentiment: "mixed",
    status: "approved",
    publishedAt: "2024-04-18T00:00:00.000Z",
  },
  {
    releaseKey: "brooks-ghost:Ghost 17",
    sourceSlug: "roadtrailrun",
    authorName: "RTR Editorial",
    sourceUrl: "https://example.com/reviews/brooks-ghost-17-rtr",
    title: "Ghost 17 stays practical while adding a little more cushion",
    excerpt:
      "The tone is positive on consistency and comfort, with the usual note that Ghost is more dependable than exciting.",
    scoreNormalized100: 81,
    originalScoreValue: "8.1",
    originalScoreScale: "10",
    sentiment: "positive",
    status: "approved",
    publishedAt: "2025-03-12T00:00:00.000Z",
  },
  {
    releaseKey: "brooks-glycerin:Glycerin 22",
    sourceSlug: "believe-in-the-run",
    authorName: "BITR Team",
    sourceUrl: "https://example.com/reviews/brooks-glycerin-22-bitr",
    title: "Glycerin 22 pushes the line further toward plush premium mileage",
    excerpt:
      "Reviewers tend to like the softness and smoothness, while noting that runners wanting more pop may look elsewhere.",
    scoreNormalized100: 88,
    originalScoreValue: "8.8",
    originalScoreScale: "10",
    sentiment: "positive",
    status: "approved",
    publishedAt: "2025-02-20T00:00:00.000Z",
  },
  {
    releaseKey: "brooks-adrenaline-gts:Adrenaline GTS 24",
    sourceSlug: "reddit-running-shoe-geeks",
    authorName: "strideforum",
    sourceUrl: "https://example.com/reviews/brooks-adrenaline-gts-24-reddit-thread",
    title: "Adrenaline GTS 24 stays in the reliable support lane",
    excerpt:
      "Community sentiment sees it as trustworthy and stable, though less appealing to runners chasing lighter and faster-feeling options.",
    scoreNormalized100: 79,
    originalScoreValue: "7.9",
    originalScoreScale: "10",
    sentiment: "mixed",
    status: "approved",
    publishedAt: "2024-09-02T00:00:00.000Z",
  },
  {
    releaseKey: "asics-gel-nimbus:GEL-Nimbus 27",
    sourceSlug: "runrepeat",
    authorName: "RunRepeat Editorial",
    sourceUrl: "https://example.com/reviews/asics-gel-nimbus-27-runrepeat",
    title: "Nimbus 27 doubles down on soft comfort for easy mileage",
    excerpt:
      "Coverage is consistently positive on softness and protection, with only the usual caveat that it is not meant to feel quick.",
    scoreNormalized100: 89,
    originalScoreValue: "8.9",
    originalScoreScale: "10",
    sentiment: "positive",
    status: "approved",
    publishedAt: "2025-01-24T00:00:00.000Z",
  },
  {
    releaseKey: "asics-novablast:Novablast 5",
    sourceSlug: "doctors-of-running",
    authorName: "Doctors of Running",
    sourceUrl: "https://example.com/reviews/asics-novablast-5-dor",
    title: "Novablast 5 gets praise for bounce and daily versatility",
    excerpt:
      "The ride is generally reviewed as energetic and fun, with some caution that it can feel unstable for runners wanting more guidance.",
    scoreNormalized100: 86,
    originalScoreValue: "8.6",
    originalScoreScale: "10",
    sentiment: "positive",
    status: "approved",
    publishedAt: "2025-01-08T00:00:00.000Z",
  },
  {
    releaseKey: "new-balance-1080:Fresh Foam X 1080v14",
    sourceSlug: "believe-in-the-run",
    authorName: "BITR Team",
    sourceUrl: "https://example.com/reviews/new-balance-1080v14-bitr",
    title: "1080v14 remains one of the cleaner mainstream comfort trainers",
    excerpt:
      "Reviewers like the smooth rocker and broad comfort range, with some noting it is softer than runners wanting firmer feedback may prefer.",
    scoreNormalized100: 87,
    originalScoreValue: "8.7",
    originalScoreScale: "10",
    sentiment: "positive",
    status: "approved",
    publishedAt: "2024-11-18T00:00:00.000Z",
  },
  {
    releaseKey: "asics-gel-kayano:GEL-Kayano 31",
    sourceSlug: "roadtrailrun",
    authorName: "RTR Editorial",
    sourceUrl: "https://example.com/reviews/asics-gel-kayano-31-rtr",
    title: "Kayano 31 stays squarely in the premium support lane",
    excerpt:
      "Reviewers like the guided comfort and long-run smoothness, with predictable tradeoffs in weight and agility.",
    scoreNormalized100: 85,
    originalScoreValue: "8.5",
    originalScoreScale: "10",
    sentiment: "positive",
    status: "approved",
    publishedAt: "2025-02-12T00:00:00.000Z",
  },
  {
    releaseKey: "asics-superblast:Superblast 2",
    sourceSlug: "believe-in-the-run",
    authorName: "BITR Team",
    sourceUrl: "https://example.com/reviews/asics-superblast-2-bitr",
    title: "Superblast 2 keeps the super-trainer slot for runners who want one shoe to do most things",
    excerpt:
      "Coverage is strongly positive on versatility and efficiency, with only modest caution around price and stack height.",
    scoreNormalized100: 92,
    originalScoreValue: "9.2",
    originalScoreScale: "10",
    sentiment: "positive",
    status: "approved",
    publishedAt: "2024-07-01T00:00:00.000Z",
  },
  {
    releaseKey: "new-balance-rebel:FuelCell Rebel v4",
    sourceSlug: "runrepeat",
    authorName: "RunRepeat Editorial",
    sourceUrl: "https://example.com/reviews/new-balance-rebel-v4-runrepeat",
    title: "Rebel v4 gains range without losing its quick personality",
    excerpt:
      "Reviewers generally like the extra substance underfoot, while keeping it in the lightweight fast-day category.",
    scoreNormalized100: 86,
    originalScoreValue: "8.6",
    originalScoreScale: "10",
    sentiment: "positive",
    status: "approved",
    publishedAt: "2024-06-12T00:00:00.000Z",
  },
  {
    releaseKey: "new-balance-more:Fresh Foam X More v5",
    sourceSlug: "doctors-of-running",
    authorName: "Doctors of Running",
    sourceUrl: "https://example.com/reviews/new-balance-more-v5-dor",
    title: "More v5 is all about comfort-first mileage",
    excerpt:
      "The general tone is positive on soft protection and easy-run comfort, with some notes that it is not designed to feel especially quick.",
    scoreNormalized100: 84,
    originalScoreValue: "8.4",
    originalScoreScale: "10",
    sentiment: "positive",
    status: "approved",
    publishedAt: "2025-01-11T00:00:00.000Z",
  },
  {
    releaseKey: "hoka-clifton:Clifton 10",
    sourceSlug: "roadtrailrun",
    authorName: "RTR Editorial",
    sourceUrl: "https://example.com/reviews/hoka-clifton-10-rtr",
    title: "Clifton 10 remains the clean HOKA daily-trainer middle ground",
    excerpt:
      "Reviewers frame it as a smoother and more current-feeling Clifton, still aimed at broad everyday road use.",
    scoreNormalized100: 83,
    originalScoreValue: "8.3",
    originalScoreScale: "10",
    sentiment: "positive",
    status: "approved",
    publishedAt: "2025-03-03T00:00:00.000Z",
  },
  {
    releaseKey: "hoka-bondi:Bondi 9",
    sourceSlug: "believe-in-the-run",
    authorName: "BITR Team",
    sourceUrl: "https://example.com/reviews/hoka-bondi-9-bitr",
    title: "Bondi 9 stays in the soft, protective comfort lane",
    excerpt:
      "Coverage emphasizes recovery-day comfort and step-in plushness, with only mild cautions about turnover and bulk.",
    scoreNormalized100: 86,
    originalScoreValue: "8.6",
    originalScoreScale: "10",
    sentiment: "positive",
    status: "approved",
    publishedAt: "2025-02-28T00:00:00.000Z",
  },
  {
    releaseKey: "hoka-cielo-x1:Cielo X1 2.0",
    sourceSlug: "runrepeat",
    authorName: "RunRepeat Editorial",
    sourceUrl: "https://example.com/reviews/hoka-cielo-x1-2-runrepeat",
    title: "Cielo X1 2.0 stays aggressive, lighter, and firmly in the fast lane",
    excerpt:
      "The review tone is positive on propulsion and race-day feel, with fit and stability remaining the main selective variables.",
    scoreNormalized100: 90,
    originalScoreValue: "9.0",
    originalScoreScale: "10",
    sentiment: "positive",
    status: "approved",
    publishedAt: "2025-03-06T00:00:00.000Z",
  },
  {
    releaseKey: "altra-torin:Torin 8",
    sourceSlug: "doctors-of-running",
    authorName: "Doctors of Running",
    sourceUrl: "https://example.com/reviews/altra-torin-8-dor",
    title: "Torin 8 keeps the zero-drop daily trainer niche well covered",
    excerpt:
      "Reviewers value the natural stance and roomy fit, with the main caveat being that zero-drop geometry is not for everyone.",
    scoreNormalized100: 82,
    originalScoreValue: "8.2",
    originalScoreScale: "10",
    sentiment: "positive",
    status: "approved",
    publishedAt: "2024-10-04T00:00:00.000Z",
  },
  {
    releaseKey: "altra-lone-peak:Lone Peak 9",
    sourceSlug: "reddit-running-shoe-geeks",
    authorName: "strideforum",
    sourceUrl: "https://example.com/reviews/altra-lone-peak-9-reddit-thread",
    title: "Lone Peak 9 keeps its trail loyalists for roomy off-road mileage",
    excerpt:
      "Community reaction is positive on fit and trail versatility, with some mixed comments on cushioning for harder terrain.",
    scoreNormalized100: 80,
    originalScoreValue: "8.0",
    originalScoreScale: "10",
    sentiment: "mixed",
    status: "approved",
    publishedAt: "2025-02-09T00:00:00.000Z",
  },
  {
    releaseKey: "mizuno-wave-rider:Wave Rider 28",
    sourceSlug: "roadtrailrun",
    authorName: "RTR Editorial",
    sourceUrl: "https://example.com/reviews/mizuno-wave-rider-28-rtr",
    title: "Wave Rider 28 keeps the traditional daily trainer audience in mind",
    excerpt:
      "Editorial reviews see it as dependable and smooth, especially for runners who still like a more classic training feel.",
    scoreNormalized100: 81,
    originalScoreValue: "8.1",
    originalScoreScale: "10",
    sentiment: "positive",
    status: "approved",
    publishedAt: "2024-09-25T00:00:00.000Z",
  },
  {
    releaseKey: "puma-deviate-nitro:Deviate NITRO 3",
    sourceSlug: "runrepeat",
    authorName: "RunRepeat Editorial",
    sourceUrl: "https://example.com/reviews/puma-deviate-nitro-3-runrepeat",
    title: "Deviate NITRO 3 still feels like a strong fast-day value",
    excerpt:
      "The review tone is positive on propulsion and training utility, with some caution that it sits firmer than the softest plated trainers.",
    scoreNormalized100: 87,
    originalScoreValue: "8.7",
    originalScoreScale: "10",
    sentiment: "positive",
    status: "approved",
    publishedAt: "2024-09-18T00:00:00.000Z",
  },
  {
    releaseKey: "puma-velocity-nitro:Velocity NITRO 3",
    sourceSlug: "believe-in-the-run",
    authorName: "BITR Team",
    sourceUrl: "https://example.com/reviews/puma-velocity-nitro-3-bitr",
    title: "Velocity NITRO 3 keeps the all-around daily role simple",
    excerpt:
      "Coverage likes the balance of comfort and versatility, with the usual note that it is more practical than flashy.",
    scoreNormalized100: 83,
    originalScoreValue: "8.3",
    originalScoreScale: "10",
    sentiment: "positive",
    status: "approved",
    publishedAt: "2024-08-22T00:00:00.000Z",
  },
  {
    releaseKey: "adidas-adizero-boston:Adizero Boston 13",
    sourceSlug: "roadtrailrun",
    authorName: "RTR Editorial",
    sourceUrl: "https://example.com/reviews/adidas-boston-13-rtr",
    title: "Boston 13 remains a firmer, more serious workout trainer",
    excerpt:
      "Reviewers frame it as a good fit for runners who like stable efficiency, while acknowledging it is not the easiest-going daily option.",
    scoreNormalized100: 84,
    originalScoreValue: "8.4",
    originalScoreScale: "10",
    sentiment: "positive",
    status: "approved",
    publishedAt: "2025-01-16T00:00:00.000Z",
  },
  {
    releaseKey: "adidas-adizero-adios-pro:Adizero Adios Pro 4",
    sourceSlug: "believe-in-the-run",
    authorName: "BITR Team",
    sourceUrl: "https://example.com/reviews/adidas-adios-pro-4-bitr",
    title: "Adios Pro 4 stays near the front of the marathon-racer conversation",
    excerpt:
      "The review tone is very positive on speed and efficiency, with fit and stability as the usual selective variables.",
    scoreNormalized100: 93,
    originalScoreValue: "9.3",
    originalScoreScale: "10",
    sentiment: "positive",
    status: "approved",
    publishedAt: "2025-02-26T00:00:00.000Z",
  },
  {
    releaseKey: "salomon-aero-glide:Aero Glide 3",
    sourceSlug: "doctors-of-running",
    authorName: "Doctors of Running",
    sourceUrl: "https://example.com/reviews/salomon-aero-glide-3-dor",
    title: "Aero Glide 3 gives Salomon a more credible road-mileage comfort option",
    excerpt:
      "Reviewers like the cushioning and secure upper, with the shoe positioned more as comfortable mileage than a speed tool.",
    scoreNormalized100: 82,
    originalScoreValue: "8.2",
    originalScoreScale: "10",
    sentiment: "positive",
    status: "approved",
    publishedAt: "2025-03-01T00:00:00.000Z",
  },
  {
    releaseKey: "hoka-speedgoat:Speedgoat 6",
    sourceSlug: "roadtrailrun",
    authorName: "RTR Editorial",
    sourceUrl: "https://example.com/reviews/hoka-speedgoat-6-rtr",
    title: "Speedgoat 6 stays near the front of the technical-trail conversation",
    excerpt:
      "Reviewers continue to like the grip and protection, with only moderate notes around fit preference and firmness for some runners.",
    scoreNormalized100: 89,
    originalScoreValue: "8.9",
    originalScoreScale: "10",
    sentiment: "positive",
    status: "approved",
    publishedAt: "2024-05-17T00:00:00.000Z",
  },
  {
    releaseKey: "brooks-cascadia:Cascadia 18",
    sourceSlug: "doctors-of-running",
    authorName: "Doctors of Running",
    sourceUrl: "https://example.com/reviews/brooks-cascadia-18-dor",
    title: "Cascadia 18 continues to serve runners who want a stable trail platform",
    excerpt:
      "Coverage is positive on predictability and protection, with some runners wanting a little more snap for faster trail days.",
    scoreNormalized100: 82,
    originalScoreValue: "8.2",
    originalScoreScale: "10",
    sentiment: "positive",
    status: "approved",
    publishedAt: "2024-07-11T00:00:00.000Z",
  },
  {
    releaseKey: "saucony-peregrine:Peregrine 15",
    sourceSlug: "believe-in-the-run",
    authorName: "BITR Team",
    sourceUrl: "https://example.com/reviews/saucony-peregrine-15-bitr",
    title: "Peregrine 15 remains one of the more versatile mainstream trail options",
    excerpt:
      "Reviewers praise the balanced grip and adaptability, with the most mixed comments around underfoot softness on longer days.",
    scoreNormalized100: 84,
    originalScoreValue: "8.4",
    originalScoreScale: "10",
    sentiment: "positive",
    status: "approved",
    publishedAt: "2025-01-19T00:00:00.000Z",
  },
  {
    releaseKey: "nike-pegasus-trail:Pegasus Trail 5",
    sourceSlug: "runrepeat",
    authorName: "RunRepeat Editorial",
    sourceUrl: "https://example.com/reviews/nike-pegasus-trail-5-runrepeat",
    title: "Pegasus Trail 5 stays strongest as a road-to-trail crossover",
    excerpt:
      "The tone is positive on versatility and comfort, while more technical trail runners still want a more aggressive outsole.",
    scoreNormalized100: 81,
    originalScoreValue: "8.1",
    originalScoreScale: "10",
    sentiment: "positive",
    status: "approved",
    publishedAt: "2024-08-09T00:00:00.000Z",
  },
  {
    releaseKey: "asics-trabuco-max:Trabuco Max 4",
    sourceSlug: "roadtrailrun",
    authorName: "RTR Editorial",
    sourceUrl: "https://example.com/reviews/asics-trabuco-max-4-rtr",
    title: "Trabuco Max 4 leans heavily into long-distance trail comfort",
    excerpt:
      "Reviewers generally like the cushioning and rollover, with some caveats that the shoe is less agile on tighter terrain.",
    scoreNormalized100: 85,
    originalScoreValue: "8.5",
    originalScoreScale: "10",
    sentiment: "positive",
    status: "approved",
    publishedAt: "2025-02-02T00:00:00.000Z",
  },
  {
    releaseKey: "adidas-terrex-agravic-speed-ultra:Terrex Agravic Speed Ultra 2",
    sourceSlug: "reddit-running-shoe-geeks",
    authorName: "strideforum",
    sourceUrl: "https://example.com/reviews/adidas-terrex-agravic-speed-ultra-2-reddit-thread",
    title: "Agravic Speed Ultra 2 gets strong feedback for mountain speed, but remains niche",
    excerpt:
      "Community sentiment is positive on speed and long-distance efficiency, with fit and technical specificity keeping it selective.",
    scoreNormalized100: 83,
    originalScoreValue: "8.3",
    originalScoreScale: "10",
    sentiment: "mixed",
    status: "approved",
    publishedAt: "2025-03-05T00:00:00.000Z",
  },
  {
    releaseKey: "salomon-speedcross:Speedcross 6",
    sourceSlug: "runrepeat",
    authorName: "RunRepeat Editorial",
    sourceUrl: "https://example.com/reviews/salomon-speedcross-6-runrepeat",
    title: "Speedcross 6 still owns the grip-first muddy-trail niche",
    excerpt:
      "Reviewers continue to value the traction and foothold, while noting that the ride is more specialized than all-round trail trainers.",
    scoreNormalized100: 86,
    originalScoreValue: "8.6",
    originalScoreScale: "10",
    sentiment: "positive",
    status: "approved",
    publishedAt: "2024-10-21T00:00:00.000Z",
  },
];

export const seedCrawlSources: SeedCrawlSource[] = [
  {
    reviewSourceSlug: "believe-in-the-run",
    importerKey: "believe-in-the-run",
    targetType: "search",
    targetUrl: "https://believeintherun.com/",
    searchPattern: "{shoe_name}",
    cadenceLabel: "daily",
    notes: "Search site content for shoe model names and capture matching editorial reviews.",
  },
  {
    reviewSourceSlug: "reddit-running-shoe-geeks",
    importerKey: "reddit-running-shoe-geeks",
    targetType: "search",
    targetUrl: "https://www.reddit.com/r/RunningShoeGeeks/",
    searchPattern: "{shoe_name}",
    cadenceLabel: "twice-daily",
    notes: "Search subreddit threads and comments for shoe model sentiment and review discussions.",
  },
  {
    reviewSourceSlug: "runrepeat",
    importerKey: "runrepeat",
    targetType: "search",
    targetUrl: "https://runrepeat.com/catalog/search",
    searchPattern: "{brand_name} {shoe_name}",
    cadenceLabel: "manual",
    notes: "Planned importer for structured review and spec extraction from RunRepeat.",
  },
  {
    reviewSourceSlug: "doctors-of-running",
    importerKey: "doctors-of-running",
    targetType: "search",
    targetUrl: "https://www.doctorsofrunning.com/search",
    searchPattern: "{brand_name} {shoe_name}",
    cadenceLabel: "manual",
    notes: "Planned importer for long-form editorial reviews from Doctors of Running.",
  },
];
