# Generated by Django 5.0 on 2023-12-23 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Reviewer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("website", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Shoe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("foam", models.CharField(max_length=200)),
                ("model_number", models.IntegerField(null=True)),
                ("release_year", models.IntegerField(null=True)),
                ("weight_ounces", models.FloatField(null=True)),
                ("heel_stack_mm", models.IntegerField(null=True)),
                ("forefoot_stack_mm", models.IntegerField(null=True)),
                ("drop_mm", models.IntegerField(null=True)),
                ("is_plated", models.BooleanField(default=False)),
                ("is_current", models.BooleanField()),
                (
                    "sport",
                    models.CharField(
                        choices=[
                            ("rr", "Road Running"),
                            ("tr", "Trail Running"),
                            ("cc", "Cross Country"),
                            ("tf", "Track & Field"),
                        ],
                        default="rr",
                        max_length=2,
                    ),
                ),
                (
                    "usage",
                    models.CharField(
                        choices=[("d", "Daily"), ("r", "Racing")],
                        default="d",
                        max_length=1,
                    ),
                ),
                (
                    "stability",
                    models.CharField(
                        choices=[("s", "Stable"), ("n", "Neutral")],
                        default="n",
                        max_length=1,
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shoes.brand",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating_numerator", models.IntegerField()),
                ("rating_denominator", models.IntegerField()),
                ("review_text", models.TextField()),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shoes.reviewer"
                    ),
                ),
                (
                    "shoe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shoes.shoe"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Colorway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "shoe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shoes.shoe"
                    ),
                ),
            ],
        ),
    ]
