# Generated by Django 5.0 on 2023-12-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shoes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="url",
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating_denominator",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating_numerator",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="review_text",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="reviewer",
            name="website",
            field=models.URLField(max_length=500, null=True),
        ),
    ]
